### ISSUE TITLE
add github topics to this project

### ISSUE THREAD

**Issue by goern** [thoth-station/ash-api#3]
so that people and bots know what this is about

**Comment by ddehueck** [comment]
@goern I don't seem to have the ability to add topics to this repo, but here is my current selection for topics: "embedding-space-traversal" and "representation-learning"

**Comment by fridex** [comment]
> @goern I don't seem to have the ability to add topics to this repo, but here is my current selection for topics: "embedding-space-traversal" and "representation-learning"

Add you to repository collaborator. You should have access now. Feel free to reopen if that's not the case.
